using System;
using System.Net;
using System.Text.Json.Serialization;
using JetBrains.Annotations;

namespace Rsdn.Api.Models.Errors
{
	/// <summary>
	/// RSDN API error. Compliant with RFC 7807.
	/// </summary>
	[PublicAPI]
	public class RsdnServiceError
	{
		/// <summary>
		/// A URI reference [RFC3986] that identifies the problem type. This specification encourages that, when
		/// dereferenced, it provide human-readable documentation for the problem type (e.g.,
		/// using HTML [W3C.REC-html5-20141028]). When this member is not present, its value is assumed to be "about:blank".
		/// </summary>
		[JsonPropertyName("type")]
		public string Type { get; set; } = "about:blank";

		/// <summary>
		/// A short, human-readable summary of the problem type. It SHOULD NOT change from occurrence to occurrence of the
		/// problem, except for purposes of localization (e.g., using proactive content negotiation; see [RFC7231],
		/// Section 3.4).
		/// </summary>
		[JsonPropertyName("title")]
		public string Title { get; set; }

		/// <summary>
		/// The HTTP status code ([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.
		/// </summary>
		[JsonPropertyName("status")]
		public HttpStatusCode Status { get; set; }

		/// <summary>
		/// A human-readable explanation specific to this occurrence of the problem.
		/// </summary>
		[JsonPropertyName("detail")]
		public string Detail { get; set; }

		/// <summary>
		/// A URI reference that identifies the specific occurrence of the problem. It may or may not yield further
		/// information if dereferenced.
		/// </summary>
		[JsonPropertyName("instance")]
		public string Instance { get; set; }

		/// <summary>
		/// Extension. List of error parameters.
		/// </summary>
		[JsonPropertyName("errorParams")]
		public ErrorParam[] ErrorParams { get; set; } = Array.Empty<ErrorParam>();

		/// <summary>
		/// Extension. Error severity.
		/// </summary>
		[JsonPropertyName("severity")]
		public ErrorSeverity Severity { get; set; }
	}
}